import type { Category, Order, Product, Review } from "@/types";

const now = new Date().toISOString();

export const demoCategories: Category[] = [
  {
    id: "cat-kids",
    name: "Kids",
    slug: "kids",
    description: "Fun, cute, and trendy.",
    image_url: "/demo/photos/kids-category.png",
    display_order: 10,
    created_at: now,
  },
  {
    id: "cat-ladies",
    name: "Ladies",
    slug: "ladies",
    description: "Style for every you.",
    image_url: "/demo/photos/ladies-category.png",
    display_order: 20,
    created_at: now,
  },
  {
    id: "cat-toys",
    name: "Toys",
    slug: "toys",
    description: "Play, learn, and have fun.",
    image_url: "/demo/photos/toys-category.png",
    display_order: 30,
    created_at: now,
  },
  {
    id: "cat-jewellery",
    name: "Jewellery",
    slug: "jewellery",
    description: "Sparkle every moment.",
    image_url: "/demo/photos/jewellery-category.png",
    display_order: 40,
    created_at: now,
  },
  {
    id: "cat-gifts",
    name: "Gifts",
    slug: "gifts",
    description: "For every occasion.",
    image_url: "/demo/photos/gifts-category.png",
    display_order: 50,
    created_at: now,
  },
];

export const demoProducts: Product[] = [
  {
    id: "prod-floral-frock",
    name: "Floral Frock",
    slug: "floral-frock",
    description:
      "Pink floral frock with a soft party-ready finish.",
    price: 2499,
    original_price: 3999,
    category_id: "cat-ladies",
    category: demoCategories[1],
    stock_quantity: 40,
    is_active: true,
    is_featured: true,
    rating_average: 4.4,
    review_count: 38,
    attribute_tag: "apparel",
    weight_grams: null,
    images: [
      {
        image_url:
          "/demo/photos/floral-frock.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-denim-jacket",
    name: "Denim Jacket",
    slug: "denim-jacket",
    description:
      "Everyday denim jacket for easy layering.",
    price: 2999,
    original_price: 4999,
    category_id: "cat-ladies",
    category: demoCategories[1],
    stock_quantity: 28,
    is_active: true,
    is_featured: true,
    rating_average: 4.6,
    review_count: 52,
    attribute_tag: "apparel",
    weight_grams: null,
    images: [
      {
        image_url:
          "/demo/photos/denim-jacket.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-teddy-bear",
    name: "Teddy Bear",
    slug: "teddy-bear",
    description:
      "Soft teddy bear for gifting and playtime.",
    price: 1999,
    original_price: 2999,
    category_id: "cat-toys",
    category: demoCategories[2],
    stock_quantity: 16,
    is_active: true,
    is_featured: true,
    rating_average: 4.2,
    review_count: 24,
    attribute_tag: "toys",
    weight_grams: null,
    images: [
      {
        image_url:
          "/demo/photos/teddy-bear.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-gold-pendant-necklace",
    name: "Gold Pendant Necklace",
    slug: "gold-pendant-necklace",
    description:
      "Beautiful gold pendant necklace for everyday wear and gifting.",
    price: 25000,
    original_price: 30000,
    category_id: "cat-jewellery",
    category: demoCategories[3],
    stock_quantity: 15,
    is_active: true,
    is_featured: false,
    rating_average: 4.8,
    review_count: 17,
    attribute_tag: "jewellery",
    weight_grams: 5.2,
    images: [
      {
        image_url:
          "/demo/photos/heart-pendant.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-birthday-gift-box",
    name: "Birthday Gift Box",
    slug: "birthday-gift-box",
    description:
      "Ready-to-gift present with special wrapping and a surprise theme.",
    price: 999,
    original_price: 1299,
    category_id: "cat-gifts",
    category: demoCategories[4],
    stock_quantity: 22,
    is_active: true,
    is_featured: true,
    rating_average: 4.3,
    review_count: 29,
    attribute_tag: "gifts",
    weight_grams: null,
    images: [
      {
        image_url:
          "/demo/photos/gifts-category.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-plush-teddy-bear",
    name: "Plush Teddy Bear",
    slug: "plush-teddy-bear",
    description:
      "Soft plush teddy bear for gifting and everyday cuddles.",
    price: 749,
    original_price: 999,
    category_id: "cat-gifts",
    category: demoCategories[4],
    stock_quantity: 35,
    is_active: true,
    is_featured: false,
    rating_average: 4.5,
    review_count: 21,
    attribute_tag: "gifts",
    weight_grams: null,
    images: [
      {
        image_url:
          "/demo/photos/teddy-bear.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-party-decoration-kit",
    name: "Party Decoration Kit",
    slug: "party-decoration-kit",
    description:
      "Birthday-ready decoration kit with banners, balloons, and table accents.",
    price: 599,
    original_price: 799,
    category_id: "cat-gifts",
    category: demoCategories[4],
    stock_quantity: 50,
    is_active: true,
    is_featured: true,
    rating_average: 4.1,
    review_count: 33,
    attribute_tag: "gifts",
    weight_grams: null,
    images: [
      {
        image_url:
          "/demo/photos/kids-play-set.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "prod-silver-charm-bracelet",
    name: "Silver Charm Bracelet",
    slug: "silver-charm-bracelet",
    description:
      "Delicate silver charm bracelet with a polished finish.",
    price: 12999,
    original_price: 15999,
    category_id: "cat-jewellery",
    category: demoCategories[3],
    stock_quantity: 18,
    is_active: true,
    is_featured: false,
    rating_average: 4.7,
    review_count: 27,
    attribute_tag: "jewellery",
    weight_grams: 4.5,
    images: [
      {
        image_url:
          "/demo/photos/jewellery-category.png",
        is_primary: true,
        display_order: 0,
      },
    ],
    created_at: now,
    updated_at: now,
  },
];

export const demoOrders: Order[] = [
  {
    id: "demo-order-1",
    order_number: "AM-DEMO-001",
    customer_email: "customer@example.com",
    status: "out_for_delivery",
    subtotal: 26299,
    shipping_charge: 0,
    total: 26299,
    shipping_name: "Demo Customer",
    shipping_address: "MG Road",
    shipping_city: "Bengaluru",
    shipping_state: "Karnataka",
    shipping_pincode: "560001",
    shipping_phone: "9876543210",
    payment_method: "cod",
    payment_status: "pending",
    items: [
      {
        product_id: "prod-gold-pendant-necklace",
        product_name: "Gold Pendant Necklace",
        product_image: demoProducts[3].images[0].image_url,
        price: 25000,
        quantity: 1,
        total: 25000,
      },
      {
        product_id: "prod-birthday-gift-box",
        product_name: "Birthday Gift Box",
        product_image: demoProducts[4].images[0].image_url,
        price: 1299,
        quantity: 1,
        total: 1299,
      },
    ],
    created_at: now,
    updated_at: now,
  },
];

export const demoReviews: Review[] = [
  {
    id: "review-company-1",
    product_id: null,
    review_target: "company",
    user_id: null,
    customer_name: "Aaradhya S.",
    customer_email: "aaradhya@example.com",
    rating: 5,
    review_text: "Lovely packaging, fast support, and the gifts looked premium.",
    media_urls: ["/demo/photos/gifts-category.png"],
    is_verified_purchase: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "review-product-1",
    product_id: "prod-floral-frock",
    review_target: "product",
    user_id: null,
    customer_name: "Priya M.",
    customer_email: "priya@example.com",
    rating: 5,
    review_text: "The frock quality is soft and the color looks exactly as expected.",
    media_urls: ["/demo/photos/floral-frock.png"],
    is_verified_purchase: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "review-product-2",
    product_id: "prod-teddy-bear",
    review_target: "product",
    user_id: null,
    customer_name: "Neha R.",
    customer_email: "neha@example.com",
    rating: 4,
    review_text: "Cute teddy, good size, and perfect for gifting.",
    media_urls: ["/demo/photos/teddy-bear.png"],
    is_verified_purchase: true,
    created_at: now,
    updated_at: now,
  },
];
